CREATE TABLE post (
	id VARCHAR(50) PRIMARY KEY,
	num_comments INT,
	created TIMESTAMP,
	score INT,
	distinguish_type VARCHAR(100),
	is_locked	BOOLEAN,
	is_stickied	BOOLEAN,
	title		TEXT,
	author		TEXT,
	author_id	VARCHAR(50),
	domain		TEXT,
	view_count	INT,
	gold_count	INT,
	is_archived	BOOLEAN,
	contest_mode	BOOLEAN,
	suggested_sort	VARCHAR(100),
	hidden	BOOLEAN,
	saved	BOOLEAN,
	is_gildable	BOOLEAN,
	is_sponsored	BOOLEAN,
	is_NSFW	BOOLEAN,
	is_meta	BOOLEAN,
	is_spoiler	BOOLEAN,
	is_blank	BOOLEAN,
	send_replies	BOOLEAN,
	vote_state	INT,
	permalink	TEXT,
	preview	TEXT,
	num_crossports	INT,
	is_crossportable	BOOLEAN,
	live_comments_websocket	TEXT,
	is_original_content	BOOLEAN,
	is_score_hidden	BOOLEAN

)
